version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - export BUCKET=codepipeline-us-east-2-416032750178
      - aws cloudformation package --template-file url-shortener.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml --debug
artifacts:
  type: zip
  files:
    - url-shortener.yaml
    - outputtemplate.yaml
